basePath: /api/v1
definitions:
  models.ChangePasswordRequest:
    properties:
      confirm_password:
        example: Newsecurep@ssword123
        type: string
      current_password:
        example: Securep@ssword123
        type: string
      new_password:
        example: Newsecurep@ssword123
        maxLength: 100
        minLength: 8
        type: string
    required:
    - confirm_password
    - current_password
    - new_password
    type: object
  models.CreateTodoRequest:
    properties:
      deadline:
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - deadline
    - title
    type: object
  models.LoginRequest:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: Securep@ssword123
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  models.RecoverPasswordRequest:
    properties:
      email:
        example: john@example.com
        type: string
    required:
    - email
    type: object
  models.RefreshAccessTokenRequest:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    required:
    - refresh_token
    type: object
  models.RegisterRequest:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: Securep@ssword123
        minLength: 8
        type: string
      username:
        example: john_doe
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.ResetPasswordRequest:
    properties:
      new_password:
        example: Newsecurep@ssword123
        minLength: 8
        type: string
      token:
        example: recovery_token_123
        type: string
    required:
    - new_password
    - token
    type: object
  models.UpdateProfileRequest:
    properties:
      email:
        example: john.updated@example.com
        type: string
      username:
        example: john_doe_updated
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - username
    type: object
  models.UpdateTodoRequest:
    properties:
      completed:
        type: boolean
      deadline:
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: https://www.youtube.com/watch?v=KsB99Sf_fX0
    name: API Support
    url: https://www.youtube.com/watch?v=KsB99Sf_fX0
  description: This is a sample Todo API server built with Go Fiber
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go Backend Todo API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Authentication
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Log out the currently authenticated user
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: User logout
      tags:
      - Authentication
  /auth/recover-password:
    post:
      consumes:
      - application/json
      description: Send password reset email
      parameters:
      - description: Recovery email data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RecoverPasswordRequest'
      produces:
      - application/json
      responses: {}
      summary: Password recovery
      tags:
      - Authentication
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh the access token for the currently authenticated user
      parameters:
      - description: Refresh token data
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/models.RefreshAccessTokenRequest'
      produces:
      - application/json
      responses: {}
      summary: Refresh access token
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: User registration
      tags:
      - Authentication
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password with recovery token
      parameters:
      - description: Password reset data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordRequest'
      produces:
      - application/json
      responses: {}
      summary: Reset password
      tags:
      - Authentication
  /auth/verify-email/{token}:
    get:
      consumes:
      - application/json
      description: Verify user email with verification token
      parameters:
      - description: Email verification token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Verify email address
      tags:
      - Authentication
  /todos:
    get:
      consumes:
      - application/json
      description: Retrieve a paginated list of todos for the authenticated user with
        optional filters
      parameters:
      - description: 'Number of items per page (default: 10)'
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - description: 'Number of items to skip (default: 0)'
        in: query
        minimum: 0
        name: offset
        type: integer
      - description: Filter by completion status
        in: query
        name: completed
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: Paginated list of todos
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid query parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized - missing or invalid token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get user's todos with pagination and filters
      tags:
      - Todos
    post:
      consumes:
      - application/json
      description: Create a new todo item for the authenticated user
      parameters:
      - description: Todo creation data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.CreateTodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Todo created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized - missing or invalid token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new todo
      tags:
      - Todos
  /todos/{id}:
    delete:
      consumes:
      - application/json
      description: Permanently delete a todo item
      parameters:
      - description: Todo ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete todo
      tags:
      - Todos
    get:
      consumes:
      - application/json
      description: Retrieve a specific todo item by its unique identifier
      parameters:
      - description: Todo ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get todo by ID
      tags:
      - Todos
    put:
      consumes:
      - application/json
      description: Update an existing todo item's information
      parameters:
      - description: Todo ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Todo update data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.UpdateTodoRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update todo
      tags:
      - Todos
  /todos/{id}/toggle:
    patch:
      consumes:
      - application/json
      description: Toggle the completion status of a todo item (completed/incomplete)
      parameters:
      - description: Todo ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Toggle todo completion status
      tags:
      - Todos
  /todos/stats:
    get:
      consumes:
      - application/json
      description: Retrieve statistics about user's todos (total, completed, incomplete)
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get todo statistics
      tags:
      - Todos
  /todos/status/{status}:
    get:
      consumes:
      - application/json
      description: Retrieve todos filtered by their completion status (completed or
        incomplete)
      parameters:
      - description: Todo status
        enum:
        - completed
        - incomplete
        in: path
        name: status
        required: true
        type: string
      - description: 'Number of items per page (default: 10)'
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - description: 'Number of items to skip (default: 0)'
        in: query
        minimum: 0
        name: offset
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get todos by completion status
      tags:
      - Todos
  /users/change-password:
    put:
      consumes:
      - application/json
      description: Change the password for the currently authenticated user
      parameters:
      - description: Password change data
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/models.ChangePasswordRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - Users
  /users/profile:
    delete:
      consumes:
      - application/json
      description: Permanently delete the currently authenticated user's account and
        all associated data
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete current user account
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Retrieve the profile information of the currently authenticated
        user
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get current user profile
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update the profile information of the currently authenticated user
      parameters:
      - description: Profile update data
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.UpdateProfileRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update current user profile
      tags:
      - Users
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Enter JWT token with Bearer prefix (e.g., Bearer your_token_here)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
